export default {
    image: "https://picsum.photos/600/500",
    huge: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempus eros suscipit ligula aliquet pulvinar. Donec vel mauris neque. Praesent aliquam purus a libero ullamcorper rutrum. Morbi dictum efficitur lacus, in imperdiet sem vestibulum ac. Maecenas vel diam a purus porttitor vestibulum suscipit nec est. Pellentesque et ex enim. Curabitur tristique est at posuere blandit. Curabitur viverra nisl at mi interdum aliquet. Quisque luctus, enim id tempor luctus, leo metus auctor eros, non maximus ante nunc eget ipsum.\n" +
        "\n" +
        "Nullam non maximus sem. Aenean quis posuere leo. Cras ac metus at enim varius maximus. Curabitur ultricies ornare metus vel vestibulum. Quisque ullamcorper, leo eu vestibulum feugiat, nunc urna hendrerit dui, et consectetur dui libero sit amet justo. Aenean mauris magna, facilisis id varius at, posuere non nunc. Proin consequat sem risus, in maximus lacus posuere sit amet. Integer quis arcu sit amet massa convallis lacinia. Proin porttitor, ex eu maximus porttitor, purus purus accumsan turpis, a dapibus urna nisi vitae erat. Praesent urna felis, porttitor in faucibus euismod, auctor eget ante. Nam iaculis, quam id elementum luctus, tellus neque laoreet est, eget lobortis sem turpis sit amet felis. Nam in erat eu enim hendrerit ultricies. Morbi viverra arcu eget luctus consectetur.\n" +
        "\n" +
        "Nullam commodo libero vel justo convallis, at dapibus massa dictum. Cras congue volutpat eros, vitae efficitur dolor rhoncus id. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum lobortis gravida sem at interdum. Proin aliquam quis orci at blandit. Suspendisse rhoncus accumsan tellus, vel aliquam risus pulvinar a. Proin quam nisi, porttitor eu ipsum in, accumsan vestibulum arcu. Proin et velit dolor. Phasellus sed enim vel dui ultrices rhoncus id ac neque. Proin id lorem sit amet orci scelerisque consequat. Vestibulum ac vulputate sapien. Sed augue nulla, gravida non pulvinar id, aliquam in ipsum.\n" +
        "\n" +
        "Cras augue justo, efficitur non eleifend at, ullamcorper eget dolor. Sed magna mauris, malesuada a nisi scelerisque, imperdiet dignissim dui. In ut dolor molestie, congue augue nec, ornare enim. Nam non sodales dui. Vivamus sed lorem in sem venenatis malesuada. Donec quis nisi tristique, tempor urna eu, commodo dolor. Maecenas ac imperdiet purus.\n" +
        "\n" +
        "Aenean risus mi, posuere tristique dolor eget, ultricies vehicula mi. In interdum ligula ex, viverra vulputate orci posuere quis. Curabitur quis sem eu ligula ullamcorper ornare sollicitudin nec nulla. Nulla vel eleifend augue. Nam congue elit ut massa ultrices, auctor egestas neque pulvinar. Mauris tempor eros tempus facilisis fringilla. Vestibulum fringilla, ligula vel sagittis ornare, nunc felis auctor nulla, vitae ullamcorper orci turpis eget justo. Fusce laoreet vulputate leo, id bibendum purus efficitur eget. Nam ac diam ut mauris elementum aliquam a in dui. Morbi tincidunt justo sit amet est dignissim, at euismod mi pretium. Proin non faucibus lorem. Curabitur et enim vel lorem iaculis semper eget a odio. Mauris egestas consequat felis eget gravida. Maecenas pretium mattis odio, ac faucibus metus pellentesque ac.",
    description: "Voluptate sunt Lorem elit cupidatat do consequat ad excepteur proident commodo aliquip. Eiusmod anim ex nisi culpa pariatur voluptate elit ex. Officia qui fugiat anim exercitation mollit qui reprehenderit nulla. Deserunt ad aute laborum ea Lorem nostrud adipisicing sint cillum aliquip. Laborum ut id proident excepteur. Laborum velit nulla laborum veniam non aliquip anim esse pariatur deserunt.",
}